(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const moods={
'muy-bien':{i:'🌞',t:'Qué bonito sentirte así.',x:'Disfruta este momento sin sentir que tienes que aprovecharlo al máximo.',w:'',wt:'Un día luminoso',wx:'Quédate un momento aquí. No tienes que correr hacia lo siguiente.',r:'Conserva un poquito de este momento.'},
bien:{i:'🌿',t:'Está bien.',x:'Gracias por decir cómo te sientes. Vamos paso a paso.',w:'',wt:'Un día tranquilo',wx:'No necesitas cambiarlo todo hoy. Un pequeño paso también cuenta.',r:'Una pequeña pausa'},
regular:{i:'🌤️',t:'Tiene sentido tener días así.',x:'No necesitas justificar lo que sientes. Podemos empezar por algo pequeño.',w:'cloudy',wt:'El cielo está un poco nublado',wx:'Que haya nubes no significa que el día esté perdido.',r:'Hoy puedes ir despacio.'},
mal:{i:'🌧️',t:'Siento que estés pasando por esto.',x:'No vamos a exigirle a este momento más de lo que puede dar. Primero, bajemos el ritmo.',w:'rainy',wt:'Está lloviendo un poco',wx:'No tienes que arreglar la tormenta de una vez. Primero ponte a salvo y respira.',r:'Primero estabilizar, después decidir.'},
'muy-mal':{i:'🤍',t:'Gracias por contarlo.',x:'Ahora mismo no necesitas hacerlo todo. Busca compañía y concéntrate en el siguiente paso seguro.',w:'night',wt:'Hagamos una pausa',wx:'Cuando todo pesa, reducir el momento a un solo paso puede ayudar.',r:'Quédate con el siguiente minuto.'}};
const quotes=[['Reflexión','Cada día puede comenzar de nuevo.','Una pausa también es avanzar.'],['Reflexión','No tienes que tener todo resuelto para seguir adelante.','Un paso pequeño sigue siendo un paso.'],['Versículo','“Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.”','Eclesiastés 3:1'],['Versículo','“El Señor está cerca de los quebrantados de corazón.”','Salmos 34:18'],['Versículo','“No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios.”','Isaías 41:10'],['Versículo','“Echa sobre el Señor tu carga, y él te sustentará.”','Salmos 55:22'],['Reflexión','Descansar no significa rendirse.','Tu bienestar también merece espacio.']];
const learn={ansiedad:'La ansiedad es una respuesta de alarma del cuerpo y la mente. Puede aparecer ante una amenaza real o anticipada. A veces ayuda a prepararnos; cuando es intensa o persistente puede ser útil hablar con un profesional.',tdah:'En el TDAH pueden existir dificultades con atención, organización, memoria de trabajo y regulación del impulso. No significa falta de inteligencia ni de voluntad. Temporizadores, listas visibles y tareas pequeñas pueden ayudar.',rumiacion:'Rumiar es quedarse atrapado dando vueltas a un pensamiento sin llegar a una acción útil. Puedes escribirlo, separar lo que controlas de lo que no y elegir una acción pequeña.',emociones:'Las emociones aportan información y preparan al cuerpo para responder. No todas son instrucciones para actuar: puedes reconocer una emoción sin obedecerla inmediatamente.'};
let audio=null,rain=null,breathTimer=null,focusTimer=null,focus=600;
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.x);toast.x=setTimeout(()=>e.classList.remove('show'),2200)}
function nav(id){$$('.section').forEach(s=>s.classList.toggle('active',s.id===id));$$('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.section===id));scrollTo({top:0,behavior:'smooth'});closeMenu()}
function openMenu(){$('#drawer').classList.add('open');$('#overlay').classList.add('show')}function closeMenu(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('show')}
function audioOn(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function beep(f=500,d=.1){if(!window.AudioContext&&!window.webkitAudioContext)return;let c=audioOn(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.035,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d+.02)}
function rainSound(){if(rain)return;let c=audioOn(),b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),d=b.getChannelData(0),last=0;for(let i=0;i<d.length;i++){let w=Math.random()*2-1;last=last*.985+w*.015;d[i]=last}rain=c.createBufferSource();rain.buffer=b;rain.loop=true;let g=c.createGain();g.gain.value=.04;rain.connect(g).connect(c.destination);rain.start();$('#soundBtn').textContent='🔊'}
function stopRain(){if(rain){try{rain.stop()}catch(e){}rain=null}$('#soundBtn').textContent='🔇'}
function mood(m){let d=moods[m];document.body.dataset.mood=m;$$('.moods button').forEach(b=>b.classList.toggle('selected',b.dataset.mood===m));$('#moodIcon').textContent=d.i;$('#moodTitle').textContent=d.t;$('#moodText').textContent=d.x;$('#weatherTitle').textContent=d.wt;$('#weatherText').textContent=d.wx;$('#recommend').textContent=d.r;let w=$('#weather');w.classList.remove('rainy','cloudy','night');if(d.w)w.classList.add(d.w);if(d.w==='rainy')rainSound();else stopRain();localStorage.setItem('menteMood',m);beep(m==='muy-mal'?220:520)}
function randomQuote(){let q=quotes[Math.floor(Math.random()*quotes.length)];$('#quoteText').textContent=q[1];$('#quoteSource').textContent=q[2]}
function wall(){let a=[...quotes].sort(()=>Math.random()-.5).slice(0,6);$('#quoteWall').innerHTML=a.map(q=>`<article class="quote-tile"><span>${q[0]}</span><p>${q[1]}</p><small>${q[2]}</small></article>`).join('')}
function tool(name){nav('herramientas');setTimeout(()=>$('#tool-'+name)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
function startBreath(){if(breathTimer)return;let phase=0,left=4,ps=[['Inhala','inhale',4],['Sostén','hold',2],['Exhala','exhale',6]];let update=()=>{$('#breath').className='breath '+ps[phase][1];$('#breathLabel').textContent=ps[phase][0];$('#breathTime').textContent=left+' s'};update();breathTimer=setInterval(()=>{if(--left<=0){phase=(phase+1)%3;left=ps[phase][2];beep(phase===2?350:520)}update()},1000);toast('Sigue el círculo. Nada más.')}
function stopBreath(){clearInterval(breathTimer);breathTimer=null;$('#breath').className='breath';$('#breathLabel').textContent='Listo';$('#breathTime').textContent='0'}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function setFocus(m){focus=m*60;$('#focusTime').textContent=fmt(focus);$$('.timer-options button').forEach(b=>b.classList.toggle('active',+b.dataset.min===m))}
function startFocus(){if(focusTimer)return;focusTimer=setInterval(()=>{focus--;$('#focusTime').textContent=fmt(focus);if(focus<=0){clearInterval(focusTimer);focusTimer=null;beep(800,.25);toast('Terminaste tu bloque. Tómate una pausa.')}},1000);toast('Enfoque iniciado');beep(600)}
function resetFocus(){clearInterval(focusTimer);focusTimer=null;setFocus(+$(' .timer-options .active')?.dataset.min||10)}
function grounding(){let s=['5 cosas que puedes ver 👀','4 cosas que puedes tocar ✋','3 sonidos que puedes escuchar 👂','2 olores que puedes notar 👃','1 cosa que puedes saborear o imaginar 🍃'],i=0,b=$('#grounding');b.innerHTML=`<p>${s[0]}</p><button class="primary" id="groundNext">Siguiente</button>`;$('#groundNext').onclick=()=>{i++;if(i>=s.length){b.innerHTML='<p>Terminaste. Mira a tu alrededor y nota que estás aquí, ahora. 🤍</p>';beep(650)}else{$('#groundNext').previousElementSibling.textContent=s[i];beep(480)}}}
function saveDiary(){let t=$('#diaryText').value.trim();if(!t)return toast('Escribe algo antes de guardar.');let a=JSON.parse(localStorage.getItem('menteDiary')||'[]');a.unshift({date:new Date().toLocaleString('es-HN',{dateStyle:'medium',timeStyle:'short'}),m:$('#diaryMood').value,t});localStorage.setItem('menteDiary',JSON.stringify(a.slice(0,30)));$('#diaryText').value='';renderDiary();toast('Entrada guardada.')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderDiary(){let a=JSON.parse(localStorage.getItem('menteDiary')||'[]');$('#entries').innerHTML=a.length?a.map(e=>`<article class="entry"><div class="entry-head"><b>${esc(e.m)}</b><small>${esc(e.date)}</small></div><p>${esc(e.t)}</p></article>`).join(''):'<p class="muted">Todavía no hay entradas.</p>'}
function init(){
$('#menuBtn').onclick=openMenu;$('#closeBtn').onclick=closeMenu;$('#overlay').onclick=closeMenu;
$$('[data-section]').forEach(b=>b.onclick=()=>nav(b.dataset.section));$$('.moods button').forEach(b=>b.onclick=()=>mood(b.dataset.mood));$$('[data-tool]').forEach(b=>b.onclick=()=>tool(b.dataset.tool));
$('#newQuote').onclick=randomQuote;$('#moreQuotes').onclick=wall;$('#breathStart').onclick=()=>{audioOn();startBreath()};$('#breathStop').onclick=stopBreath;
$('#saveMind').onclick=()=>{let v=$('#mind').value.trim();if(v){localStorage.setItem('menteMind',v);toast('Guardado.')}else toast('No hay nada que guardar.')};$('#clearMind').onclick=()=>{$('#mind').value='';localStorage.removeItem('menteMind');toast('Espacio limpio.')};if(localStorage.getItem('menteMind'))$('#mind').value=localStorage.getItem('menteMind');
$$('.timer-options button').forEach(b=>b.onclick=()=>setFocus(+b.dataset.min));$('#focusStart').onclick=()=>{audioOn();startFocus()};$('#focusReset').onclick=resetFocus;$('#groundingStart').onclick=()=>{audioOn();grounding()};
$$('.learn button').forEach(b=>b.onclick=()=>$('#answer').textContent=learn[b.dataset.learn]);$('#saveDiary').onclick=saveDiary;$('#clearDiary').onclick=()=>{$('#diaryText').value='';toast('Texto limpiado.')};
$('#soundBtn').onclick=()=>rain?stopRain():rainSound();$('#ambientBtn').onclick=()=>rain?stopRain():rainSound();
randomQuote();wall();renderDiary();let m=localStorage.getItem('menteMood');if(m&&moods[m])mood(m);
}
document.addEventListener('DOMContentLoaded',init);
})();
